name: Continuous Integration and Deployment

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: blog-api-prd
  DOTNET_VERSION: "6.0.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Restore Packages
        run: dotnet restore

      - name: Build Project
        run: dotnet build -c Release --no-restore

      - name: Run Automated Tests
        run: dotnet test -c Release --no-build

      - name: Publish Project
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}

      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{env.DOTNET_ROOT}}
